### ISSUE TITLE
Add Boost Library as a Dependancy for this Project

### ISSUE THREAD

**Issue by Dcbaas** [irawoodring/gv343_game_section2#6]
### Why do I want this?

For my part of the project, I am loading in .csv files and have had a fiddly time trying to make custom parsers work. Boost has a token splitting library that is useful for this. Having this library would make it simpler to load .csv files in.

**Comment by irawoodring** [comment]
I want to recommend https://github.com/ben-strasser/fast-cpp-csv-parser instead.  It is rather full-featured, and completely contained in a single *.h file.  Check it out and let me know!
